# Schema for configuration files of the commerce product menu module.
commerce_product.commerce_product_type.*.third_party.menu_ui:
  type: mapping
  label: 'Per product type menu settings'
  mapping:
    available_menus:
      type: sequence
      label: 'Available menus'
      sequence:
       type: string
       label: 'Menu machine name'
    parent:
      type: string
      label: 'Parent'